<?php

declare(strict_types=1);

/*
 * This file is part of the StixxOpenApiCommandBundle package.
 *
 * (c) Stixx
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Stixx\OpenApiCommandBundle\Model;

use OpenApi\Attributes as OA;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @api
 */
#[OA\Schema(
    title: 'ProblemDetails',
    required: ['type', 'title', 'status'],
    externalDocs: new OA\ExternalDocumentation(
        description: 'Problem Details for HTTP APIs',
        url: 'https://datatracker.ietf.org/doc/html/rfc7807'
    )
)]
class ProblemDetails
{
    public function __construct(
        #[OA\Property(description: 'A URI reference [RFC3986] that identifies the problem type.', format: 'uri-reference', default: 'about:blank')]
        #[Assert\NotBlank]
        public string $type = 'about:blank',
        #[OA\Property(description: 'A short, human-readable summary of the problem type.', type: 'string', default: 'An error occurred')]
        public string $title = 'An error occurred',
        #[OA\Property(description: 'The HTTP status code generated by the origin server for this occurrence of the problem.', type: 'integer', default: Response::HTTP_BAD_REQUEST)]
        public int $status = 400,
        #[OA\Property(description: 'A human-readable explanation specific to this occurrence of the problem.', type: 'string')]
        public ?string $detail = null,
        #[OA\Property(description: 'A URI reference that identifies the specific occurrence of the problem.', type: 'string', format: 'uri')]
        public ?string $instance = null,
    ) {
    }
}
