name: CI
on:
  push:
    branches:
      - main
  pull_request: ~
  workflow_dispatch: ~

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: '8.4'
          extensions: json
          coverage: none
      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - name: Cache dependencies
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: lint-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: lint-composer-
      - name: Install dependencies
        run: composer update --prefer-dist
      - name: Run simple-phpunit version check
        run: ./vendor/bin/simple-phpunit --version
      - name: Run code style check
        run: composer cs-fixer -- --dry-run --diff
      - name: Run static analysis
        run: composer phpstan

  tests:
    name: Tests (PHP ${{ matrix.php }}, Symfony ${{ matrix.symfony }})
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - '8.4'
          - '8.5'
        symfony:
          - '7.3.*'
          - '8.0.*'
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: ${{ matrix.php }}
          extensions: json
          coverage: none
          tools: flex
      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - name: Cache dependencies
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ matrix.php }}-symfony-${{ matrix.symfony }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ matrix.php }}-symfony-${{ matrix.symfony }}-composer-
      - name: Install dependencies
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony }}
        run: composer update --prefer-dist --no-progress
      - name: Run tests
        run: composer test
